### PR TITLE
Pep440 versions

### PR DESCRIPTION
**Pull request by toabctl**

### CODE REVIEW

**Comment by dirkmueller** [comment]
Mm, so actually we only need the 2nd commit right now

**Comment by dirkmueller** [comment]
The code duplication seems.a bit ugly bit is necessary. I wonder if there is a way around that though.

**Comment by toabctl** [comment]
@dirkmueller I removed the first commit.

**Comment by dirkmueller** [comment]
thanks, really nice cleanup :)

**Pull request merged**
